# Generated by Django 3.2.12 on 2024-05-14 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.IntegerField(default=0)),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('masv', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('time_in', models.TimeField(default=datetime.datetime(2024, 5, 14, 6, 46, 16, 708115))),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('masv', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
