# Generated by Django 4.2.16 on 2024-10-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finger_id',
            field=models.IntegerField(default=0),
        ),
    ]
