# Generated by Django 4.2.16 on 2024-10-15 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_student_finger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
