# Generated by Django 3.2.12 on 2024-05-14 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20240514_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 7, 7, 4, 754327)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 5, 14, 7, 7, 4, 754340)),
        ),
    ]
