# Generated by Django 4.2.11 on 2024-05-15 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20240514_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 20, 40, 45, 268871)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 5, 15, 20, 40, 45, 268888)),
        ),
    ]
